plugin:
    name: 'nielsvandendries.message::lang.plugin.name'
    description: 'nielsvandendries.message::lang.plugin.description'
    author: 'Niels van den Dries'
    icon: oc-icon-envelope
    homepage: 'https://nvandendries.nl'
permissions:
    manager:
        tab: 'nielsvandendries.message::lang.plugin.name'
        label: Manager
navigation:
    main-menu-item:
        label: Messages
        url: nielsvandendries/message/messagelist
        icon: icon-envelope
        permissions:
            - manager
